### ISSUE TITLE
In PaperController#update. Should we be able to update the location via the api?

### ISSUE THREAD

**Issue by marcrohloff** [openjournals/theoj#101]

**Comment by marcrohloff** [comment]
Ditto for the arxiv_id

**Comment by stuartlynn** [comment]
Probably not. We should restrict that

**Comment by marcrohloff** [comment]
Ok I'll fix that since I'm working there

**Comment by marcrohloff** [comment]
What is the use case for updating a paper at all? For example we allow updating the title but shouldn't this only be possible by pulling a new version from Arxiv?

**Comment by marcrohloff** [comment]
Should I remove this API altogether? Ditto for the update annotation API.

**Comment by freelanceastro** [comment]
Yeah, let's remove those. I agree that the use case is unclear at best, at least for now. I can see some far-future stuff where we might possibly want API access to that stuff, but not while we're restricting submissions to the arXiv.

**Comment by marcrohloff** [comment]
The only current use case is allowing people to edit comments and replies (though I don't like systems that allow that)

**Comment by stuartlynn** [comment]
I tink we should remove the routes but lets keep the code in the controller for now. It will probably come in handy later on. 


—

**Comment by freelanceastro** [comment]
Sounds good. Someone who knows more about this than I do should add an issue for that with the right wording; I'm going to close this question.

**Comment by marcrohloff** [comment]
OK, I'll add something.
