### ISSUE TITLE
Replies to annotations

### ISSUE THREAD

**Issue by arfon** [openjournals/theoj#11]
Should be possible to reply (in the UI) to an annotation.

**Comment by stuartlynn** [comment]
resolved by #82

**Comment by marcrohloff** [comment]
Can I close this? It seems that it is already possible to reply.

**Comment by stuartlynn** [comment]
Yeah sure I am going to style them up a bit today but they are functionally there. 




Cheers




Stuart


—

**Comment by marcrohloff** [comment]
I actually just finished with some better styling and made the reply box fit better. I'm going to start working changing the annotation state (#13)

**Comment by stuartlynn** [comment]
Awesome. I am going to work on the pdf hi lighting and some tools for editors to be able to assign reviewers and change the overall state of the page.




Cheers




STuart


—
