### ISSUE TITLE
Do we want logins to last across sessions?

### ISSUE THREAD

**Issue by marcrohloff** [openjournals/theoj#117]

**Comment by stuartlynn** [comment]
Ideally but don't think this is high priority just now

**Comment by marcrohloff** [comment]
I might save more time not logging in than its going to take me to fix it :)

**Comment by stuartlynn** [comment]
Cool. If it's quick then go for it! 



—

**Comment by arfon** [comment]
> I might save more time not logging in than its going to take me to fix it :)

:+1: sounds like a good idea then :smile:
