### ISSUE TITLE
Create visually distinct styles for roles

### ISSUE THREAD

**Issue by arfon** [openjournals/theoj#12]
Roles include:

- Author / co-author 
- Editor
- Reviewer

**Comment by marcrohloff** [comment]
Where do we want this to go? On the list of papers?

**Comment by freelanceastro** [comment]
Yes, and also on the PDF view itself – when I'm looking at a PDF, I want to know what role I've got on it. There should be a small tag in the upper-right, near the open and closed issue counts, saying "author" or "editor" or "reviewer".

**Comment by marcrohloff** [comment]
Does someone want to pick some standard colors and icons (ideally from here https://www.polymer-project.org/components/core-icons/demo.html). We should probably try and be consistent across the app.

**Comment by freelanceastro** [comment]
Looking over those icons, I don't see any that look particularly appropriate for these roles; let's worry about icons later.
For now, let's just use three different colors. I used a color-picking app to find this triplet, which is probably not ideal but it'll work fine for now:
#beaed4 (blue): Authors
#7fc97f (green): Reviewers
#fdc086 (orange-red): Editors
