### ISSUE TITLE
Should be possible to change state of annotation in UI

### ISSUE THREAD

**Issue by arfon** [openjournals/theoj#13]
For states:

- Un-resolved
- Resolved/complete
- In dispute

**Comment by marcrohloff** [comment]
Which permissions are required to make which changes here?

**Comment by stuartlynn** [comment]
Reviewers and editors can change the state of a issue. Authors and
coauthors should not be able to do so.

**Comment by arfon** [comment]
Let me know if you want me to take a look into this. Shouldn't be too hard.
