### ISSUE TITLE
Allow Markdown (or at least hyperlinks) in annotations

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#131]

**Comment by marcrohloff** [comment]
Are we going to allow pure html or some version of markdown?

**Comment by stuartlynn** [comment]
This should just be markdown, not html.


—

**Comment by freelanceastro** [comment]
Should be possible to put hyperlinks into annotations, if nothing else. I don't know if we even need full Markdown.

**Comment by freelanceastro** [comment]
To clarify: we absolutely need hyperlinks. Full Markdown support would be nice, but if that turns out to be tricky for some reason, we shouldn't spend too much time on it.

**Comment by stuartlynn** [comment]
I don’t think markdown would hurt and is a relatively understood format. I think we need a way to reference other issues as well much in the same way as you can on github. I think that will be important in facilitating discussion.


—

**Comment by stuartlynn** [comment]
It should be really easy there are already some polymer components out there to do this. 

—

**Comment by freelanceastro** [comment]
@stuartlynn: are you saying that it should be easy to support full Markdown, or to allow links between comments, or both?
I agree that linking between comments would be helpful, but that should be a separate issue, unless supporting hyperlinks and markdown automatically gives us links between comments. Does it?

**Comment by stuartlynn** [comment]
If we support markdown (which should be trivial) we get hyperlinks for free. The only tricky thing might be combining mathjax and markdown but I think this is doable. 


—

**Comment by freelanceastro** [comment]
I know we get hyperlinks for free with Markdown, but do we get links between comments for free too? I don't think we do...

**Comment by freelanceastro** [comment]
As for Markdown + MathJax, perhaps this will help?
http://markx.herokuapp.com/

**Comment by stuartlynn** [comment]
That looks like it will help a lot. 


Sorry I misread your comment. Yeah we will have to implement something custom for references to other issues but we just did something similar in the journal of brief ideas which can help with what we do here I think. 




Cheers




Stuart


—

**Comment by freelanceastro** [comment]
OK, I'm going to open a separate issue for links between comments, then.

**Comment by freelanceastro** [comment]
NB: Markx is under a somewhat restrictive license, CC-BY-NC-SA 3.0, which is an awfully strange choice for code. They say "If you really want this without the NC, contact the developers," but I think SA is also a problem -- I have no idea if the MIT license counts as SA under the terms of the CC licenses. (Those were never intended to work with software licenses, I think.) So we may have to look elsewhere for MathJax + Markdown integration.

**Comment by freelanceastro** [comment]
Here's another option, under a less restrictive license (Apache):
https://github.com/benweet/stackedit

And another option: http://stackoverflow.com/questions/12069625/how-to-use-markdown-with-mathjax-like-math-stackexchange
The relevant code seems to be under the MIT license, though I don't know about the relevant license for snippets of code from StackOverflow.

Finally, there's this interesting bit of the MathJax documentation, which talks about this problem (MathJax and Markdown) explicitly: http://docs.mathjax.org/en/latest/tex.html#tex-and-latex-in-html-documents
