### ISSUE TITLE
Allow LaTeX equations in annotations

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#132]
Probably best to do this with MathJax.

**Comment by stuartlynn** [comment]
I think @arfon had a suggestion for this which wasn't mathjax

**Comment by arfon** [comment]
Yeah, best stick with MathJax for now...

**Comment by stuartlynn** [comment]
ok sounds good. 





—

**Comment by freelanceastro** [comment]
See the thread on issue #131 for Markdown and MathJax integration options; there are a few out there.

**Comment by arfon** [comment]
This was pretty easy over here: https://github.com/openjournals/brief-ideas/pull/100

Note, I pulled out the turbolinks stuff here but we wouldn't need to, we'd just need to explicitly call the Math rendering.

**Comment by pkra** [comment]
Anything I can do to help?
