### ISSUE TITLE
Show what an issue is linked to

### ISSUE THREAD

**Issue by marcrohloff** [openjournals/theoj#138]
We should probably have a marker over the pdf so that you can see what the issue is referring to. We also need to think about how to show that an issue is 'document level'.

Another possibility is to show a snippet of text near the annotation point in the annotation item.

**Comment by marcrohloff** [comment]
Is the current implementation for rgis ok

**Comment by freelanceastro** [comment]
I'm going to assume that "rgis" means "this", and your fingers were shifted over on the keyboard by one key for the first half of the word. :-)

Anyhow, yes, the current implementation is great, so I'm closing this comment.
