### ISSUE TITLE
LaTeX and Markdown work in preview but not in final comments

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#141]
Here's the preview while writing the comment:
![screen shot 2015-03-07 at 12 25 59 pm](https://cloud.githubusercontent.com/assets/3872825/6543141/6e19314a-c4c5-11e4-8185-31cb0e60b326.png)
And here's the final comment:
![screen shot 2015-03-07 at 12 26 17 pm](https://cloud.githubusercontent.com/assets/3872825/6543145/76dab588-c4c5-11e4-9c06-8ffec5162038.png)
This is all in Chrome.

**Comment by marcrohloff** [comment]
Adam, Some of this didn't survive the merge 100%. I just merged my latest PR which should fix it, if you could check.
Markup is only shown when an issue is expanded. When it is collapsed I remove anything that affects block formatting (headings, images, equations) so you only basically get things like strikeout and em (iirc not links though it could be made to work). 
Issues are already in bold (though not replies) so bold isn't visible.

**Comment by freelanceastro** [comment]
Looks good! Thanks.
