### ISSUE TITLE
Pointer from annotations to location in text

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#143]
Something along the lines of the pointers for comments in Word -- including highlighting when you expand a comment, so you know which pointer goes with the comment.

**Comment by freelanceastro** [comment]
Can we use the fix from #38 to do this easily?

**Comment by marcrohloff** [comment]
I don't think this is really relevant. I haven't figured out how to do this
yet. Drawing a line across elements is not something that html really
supports. Can we just put a marker in the text?

**Comment by freelanceastro** [comment]
A marker in text is fine, as long as it responds in some way when a comment is expanded.

**Comment by marcrohloff** [comment]
For now the markers are in the front of the text. I'm not sure how much of an issue this is.
