### ISSUE TITLE
Front page for readers

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#146]
There should be a nice front page for reading papers, where you can easily see papers that have recently been accepted by the journal.

**Comment by marcrohloff** [comment]
What exactly do you want to appear on this page?

It wouldalso  help to define the overall look of what we want the UI to be for logged in and out users, i.e. help and about pages (including their text), front page for readers, etc.

**Comment by marcrohloff** [comment]
There should now be a list of recent papers. This is the default page if you are logged out.
Additionally you can now view a paper (including its comments) in read-only mode if you are not assigned to it (or are logged out)

**Comment by marcrohloff** [comment]
I'm not sure if this is what you envisioned - please close this if it is, otherwise I could use some direction.
