### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#147]
Should be possible for readers (and others!) to easily search all papers that have been accepted by the OJ.

**Comment by marcrohloff** [comment]
Do we just want to search titles? Authors? 
Can we do a simple contains text (title =~ /search/i) or do we need a more complex free form

**Comment by freelanceastro** [comment]
Titles and authors is fine for now. Full-text search would be awesome, but I suspect that would be really hard, right?
And yes, contains text search works.

**Comment by marcrohloff** [comment]
Should be done
