### ISSUE TITLE
Set up an email address for the OJ editorial mailer

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#148]
See #33

**Comment by arfon** [comment]
We need to implement https://github.com/openjournals/theoj/issues/97 first.

**Comment by marcrohloff** [comment]
Why does this depend on #97? I need an account I can send emails from for a few tasks.
We could use one of these services too: https://elements.heroku.com/addons#email-sms

**Comment by freelanceastro** [comment]
Yeah, I don't see why this depends on #97. We need this and #97 in order to actually send the emails to authors, but that's #33. @arfon, can you get on this?
