### ISSUE TITLE
General annotations

### ISSUE THREAD

**Issue by arfon** [openjournals/theoj#15]
Just as it needs to be possible to bind annotations to content within the PDF it also needs to be possible to create a general comment about the paper (that aren't bound to a particular part of the document)

**Comment by marcrohloff** [comment]
So for this request we just want to add document level annotations?

I'll open another 'one day' issue for one-to-many seelctions

**Comment by arfon** [comment]
:+1:

**Comment by marcrohloff** [comment]
For this one would it not be easier to just set  page=0, yStart=0 ?
We also need to think about how we want to handle overlapping annotations, the biggest problem I see is an example where we have, saym 3 document level annotations.
```
A
B
C
```
I can adjust the y position to make sure there are no issues but  what happens when you uncollapse 'A'? It now hides what is underneath it.
```
A
 |
C
```
Making it non-obvious that there are other annotations.

**Comment by stuartlynn** [comment]
I think we should have annotations that are general have an explicit "general" flag as I think that page=0 and yStart=0 is semantically different and will be confusing as we go on. 

I think there are a few different ways of doing overlapping annotations. I dont have a strong preference to what we do when they overlap. @arfon @freelanceastro want to comment?

**Comment by marcrohloff** [comment]
So I'm thinking of adding a button at the top above the pdf to add a 'document issue'. Are we going to want to allow adding page level issues as well? It would probably be easiest for me to knock them both off at the same time.

**Comment by stuartlynn** [comment]
I think just document level issues and not page level. Page level can be handled by inline commenting where as larger philosophical issues with the paper need their own space. 

—

**Comment by freelanceastro** [comment]
Agreed, there's no need for page level issues. And a button at the top above the PDF sounds about right for document-level issues, though we'd want it to be clear that that's what the button is for – either text on the button or a tool-tip popping up on hover.

**Comment by marcrohloff** [comment]
We probably need to think of a way to show what annotations are linked to. I can implement the logic for these comments but there is no way to tell that a previous issue was a document level issue.
