### ISSUE TITLE
Allow editors to delete papers

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#156]

**Comment by stuartlynn** [comment]
Probably not delete but "hide" / mark as rejected right?

**Comment by marcrohloff** [comment]
Maybe we should clarify the workflow? 
- Can editors delete a paper at any point, even when it is under review?
- What does rejecting a paper do in the current workflow? 

I assume that a workflow would be something along the line of:
* Submitted
* Under Review
* All Reviewers have checked off
At this point if the Editor chooses 'Rejected' I assume that we go back to 'Under Rveiew'?
* Accepted

**Comment by freelanceastro** [comment]
This was intended simply to allow editors to delete accidental/multiple/spam submissions. It should only be possible before any reviewers are assigned.

The workflow is:

* Submitted (the only point at which deletion should be possible)
* Under Review (reviewers assigned)
* Review continues until all reviewers have checked off that they're ready for the editor to step in (which means reviewer instructions must emphasize that they shouldn't check off on a paper until the authors have had a chance to address their concerns!)
* The editor either marks the paper as Accepted or Rejected. Both of those statuses automatically trigger several simple actions (emails to authors in either case, notifications to the arXiv and alteration of the accepted papers display page for accepted papers), but none of that is part of the editorial workflow.
* Ideally, accepted AND rejected papers are automatically hidden from the editor's view, but we don't need to deal with that yet....that can be a "someday" task.

**Comment by marcrohloff** [comment]
Does 'delete' delete all versions or just one version?
Can you delete only the most recent version? 
If so what happens to the previous version?

**Comment by freelanceastro** [comment]
Since this should only be possible in the "submitted" state, before reviewers are assigned, I think deleting a paper should delete all versions. The use case (for now, at least) is accidental or duplicate submission.

Also, not to make Stuart even more godlike, but I'm thinking that this power should really be limited to the admin account, at least for now. @stuartlynn, @arfon, do you agree?

**Comment by marcrohloff** [comment]
Should be done. Since this is intended for accidental or spam submissions it is currently a permanent deletion.

**Comment by freelanceastro** [comment]
I'm seeing this, but it's behaving the opposite of the way we want -- it only appears on papers that are past the "submitted" stage, rather than *only* appearing on papers that are in that stage.

**Comment by marcrohloff** [comment]
Should be fixed now.

**Comment by freelanceastro** [comment]
Yep, looks good.

**Comment by marcrohloff** [comment]
Done
