### ISSUE TITLE
Fix annotation permissions

### ISSUE THREAD

**Issue by marcrohloff** [openjournals/theoj#159]
It is currently possible to annotate papers even if you aren't a reviewer, editor or author. It is also possible to annotate when the paper is not in the 'under_review' state.

**Comment by marcrohloff** [comment]
We might also want to use the full width for the pdf when the state is 'submitted'

**Comment by marcrohloff** [comment]
Done. Anyone who is assigned to a paper can annotate or comment on it when it is in the under review state.

**Comment by freelanceastro** [comment]
Not sure how I can even see a paper if I'm not a reviewer, editor, or author for it, so I'm not sure how to test this. @marcrohloff, any ideas?

**Comment by marcrohloff** [comment]
The second part should be relatively easy to test. I don't think that we currently allow non logged in users to view a paper at all - I think we probably want to change that. You could create a paper, assign it as reviewer one and then login as reviewer two. In that case the paper should not be editable even if it is under review.

**Comment by freelanceastro** [comment]
Right, but how could I actually see the paper as reviewer two? It wouldn't appear under papers I'm reviewing.

**Comment by marcrohloff** [comment]
Login as Reviewer One, go to the paper, copy the URL.
Login as Reviewer Two, paste the URL

Marc
​
