### ISSUE TITLE
Make it possible for authors to submit revisions through the arXiv

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#163]
On the front page of the Open Journal, we promise authors the ability to submit revisions by posting a new version of their paper to the arXiv. But right now, it's only possible to submit one version of a paper from the arXiv. Authors have to be able to submit revised versions of their papers. But the revised submissions can't simply *replace* the old submissions. So a revised submission needs to be associated with the original submission, but clearly marked as the most up-to-date version. And reviewers and editors need to retain the ability to look at the original submissions and the comments associated with them – but when they're doing so, there needs to be an indicator that there's a newer version of the paper available.

**Comment by marcrohloff** [comment]
One huge story. I think we should hash this out and break it into smaller pieces.

**Comment by freelanceastro** [comment]
OK. How about:
- Authors should be able to submit revised papers by posting new versions of the original paper to the arXiv, then submitting that new version to the OJ;
- Revised versions should be associated with the original versions in all views (author, reviewer, editor), with the newest version of a paper clearly marked;
- Reviewers and editors should be notified when a revised version has been submitted;
- Older versions of a submission should have a banner or indicator of some kind noting that there's a newer version;
- Older versions of a submission should retain their comments, but should not allow new comments.

Does that breakout look about right?

**Comment by marcrohloff** [comment]
How are we going to navigate between versions?
Do we want to copy old (maybe only unresolved) issues to the new paper?
​

**Comment by freelanceastro** [comment]
If there's multiple versions of a paper, then clicking on the paper in the "Your Papers" view should default to the newest version. Maybe a disclosure triangle within the entry in the "Your Papers" view would allow you to navigate between versions. And if you're looking at an old version, there should be a link somewhere at the top of the paper that would easily allow you to jump to the newest version.

My first impulse is to say that we don't copy *any* issues to the new paper, at least not for now, for several reasons:
- Generally, a revised copy of a paper attempts to address all issues that reviewers had with the old paper.
- New versions of a paper often have different pagination than old versions, so it'd be hard to move the comments from one version to another.
- If there are any issues that need to be moved from one version to the other, it'd be easy enough for a reviewer to go to the old version, copy the text, and use it to make a new comment.

**Comment by marcrohloff** [comment]
> Generally, a revised copy of a paper attempts to address all
> issues that reviewers had with the old paper.
Agreed, but the reviewer would want to confirm that somehow

> New versions of a paper often have different pagination than old versions,
> so it'd be hard to move the comments from one version to another.
Yes, maintaining context would be nearly imposssible. They would have
to become document level issue and we could mark them specially as
'carried issues'. I don't know if we could include text surrounding
the issues location to help the reviewer find the context )in the
future) or use some other matching algorithm.
Another option would be providing a mechanism to move an issue's start
point using drag and drop or something similar.

> If there are any issues that need to be moved from one version to the other,
> it'd be easy enough for a reviewer to go to the old version, copy the text, and use it to make a new comment.
This sounds tedious to me when we can easily do a much better job
programmatically.

**Comment by arfon** [comment]
> My first impulse is to say that we don't copy any issues to the new paper, at least not for now, for several reasons:

Yeah, I feel like we should flag them with some status such as 'pending signoff' or something.

> This sounds tedious to me when we can easily do a much better job
programmatically.

What about just have a workflow like:

- Is this issue still valid?
- If 'yes' then given reviewer a button to 'add issue to new revision' (they'd need to click where on the new paper version)
- If 'no' then just close out the issue.

**Comment by freelanceastro** [comment]
Superseded by #169, #170, and #171.
