### ISSUE TITLE
Accidental multiple posting of the same comment

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#164]
There's sometimes a lag between hitting the "add comment" button and the comment actually posting; if, in that lag, you hit the "add comment" button again, the comment is added multiple times, like so:
![screen shot 2015-04-14 at 5 49 17 pm](https://cloud.githubusercontent.com/assets/3872825/7150359/9e7050a4-e2ce-11e4-8e31-13c5f010c35a.png)
Freezing the "add comment" button after it's been pressed once should fix this.

**Comment by marcrohloff** [comment]
Done
