### ISSUE TITLE
Switch view to "Your Papers" automatically on sign-in.

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#165]
Once you've signed in, you don't really care about the Home and About pages.

**Comment by marcrohloff** [comment]
We can probably make this a bit more intelligent based on whether the user has or has no submitted any papers as well as if they are assigned as a reviewer or editor

**Comment by freelanceastro** [comment]
Yeah, that makes sense. If the user has no papers, then the view should certainly switch to "Submit."

**Comment by marcrohloff** [comment]
Should be done, the priority is /editing, /review, /papers and lastly /submit

**Comment by freelanceastro** [comment]
Looks good.
