### ISSUE TITLE
Move "Home" and "About" pages to the bottom of the navigation sidebar once users have signed in

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#166]
They're not as relevant to signed-in users.

**Comment by marcrohloff** [comment]
I don't think the home page should be at the bottom that is kind of contradictory

**Comment by marcrohloff** [comment]
Maybe we should combine them somehow. At least when logged in?

**Comment by freelanceastro** [comment]
Yeah, combining them is a good idea.

**Comment by marcrohloff** [comment]
So do we remove the home page altogether and just display the about  page
when you're logged out?

**Comment by freelanceastro** [comment]
Yes, good idea. Just put the text from the Home page at the top of the About page and call it About, and I think that'll do it.

**Comment by marcrohloff** [comment]
This should be done. Additionally the 'recent' page is now the default for logged out users.
