### ISSUE TITLE
If you can't resolve an issue, you shouldn't be able to see the "resolve" button.

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#174]
Authors can see the resolve button, but they can't actually do anything with it...

**Comment by marcrohloff** [comment]
I don't think this is correct. As currently implemented authors can use the 'resolve' button if they created the issue to start with (which I haven't prevented, I see no reason why an author cannot comment on their paper before someone else notices an issue)

**Comment by freelanceastro** [comment]
Oh, absolutely. But authors shouldn't be able to see the resolve button on reviewer comments.

**Comment by marcrohloff** [comment]
Unless I missed something, reviewers can't resolve each others comments either. An editor can resolve anyone's comments.

**Comment by freelanceastro** [comment]
Right, yes. The point is that authors shouldn't see a "resolve" button on comments they didn't write themselves.

**Comment by marcrohloff** [comment]
Are you saying they currently can?
