### ISSUE TITLE
Different reviewers should have separate identities in comment threads

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#175]
Right now, there's no way to tell which comments came from which reviewers, which makes it hard for conversations to happen.

**Comment by marcrohloff** [comment]
I assume we can use a different color for each review/author. How many authors and reviewers do we want to support so that I can have an idea of how many colors I need.
Can we use people's initials as part of the marker?

**Comment by freelanceastro** [comment]
Different colors for each reviewer is great. We'll never have more than 3 reviewers -- anything more than 2 is unusual.

No, we can't use people's initials; the community is small enough that it'd be a dead giveaway of the reviewer's identity in many cases. But we could use identicons: https://github.com/blog/1586-identicons

**Comment by marcrohloff** [comment]
I'll take a look but space might be an issue

**Comment by freelanceastro** [comment]
Fair enough. Then perhaps just give them numbered names: reviewer 1 and reviewer 2. That's how it's often done in traditional journals anyhow.

**Comment by marcrohloff** [comment]
I've already got colors mostly working. Colors are easy to show in a small
area names of any form take a lot more space. (fwiw, there are tooltips for
editors)
​
