### ISSUE TITLE
"Done reviewing" checkbox for reviewers 

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#181]
Two options for reviewers:
I'm done reviewing, and I think this paper should be accepted.
I'm done reviewing, and I think this paper should be rejected.

**Comment by marcrohloff** [comment]
This should be done. Notes
1) There is a new state between 'under review' and 'accepted' called 'review completed'. It is entered when all reviewers complete their reviews.
2) Reviewers now have a 'Mark Completed' button (only when under review and not completed)
3) Editors will get an email when ALL reviews are complete
4) When the paper is 'under review' editors can see a checkbox next to each reviewers name.
5) If a reviewer has marked his review as completed and the user submits a new version his review status will revert to uncompleted.

**Comment by freelanceastro** [comment]
The reviewer needs to be able to indicate whether they think the paper should be accepted or rejected. So the popup box should have two options (aside from "cancel"): "recommend acceptance" or "recommend rejection."

**Comment by marcrohloff** [comment]
Any ideas on how to display this since a checkbox will no longer work
​

**Comment by marcrohloff** [comment]
This is done though I suggest we rethink the text in the dialog to make it better and the buttons smaller.
The editor will now see a tri-state box next to reviewers (blank, x or checkmark) which also has a more verbose tooltip.

**Comment by chrislintott** [comment]
Don’t we need three options?

I’m done reviewing and this should be accepted
I’m done reviewing and this should be rejected
I’m done reviewing and this should be reconsidered after revision.
