### ISSUE TITLE
Editorial panel for papers

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#183]
A place where editors can see:
- the status of a paper
- who the authors are, with email addresses
- who the reviewers are/were, with email addresses
- how many issues are open and closed on the paper, if it's still in review
- the status of the "done reviewing" checkboxes for all the reviewers

This information could just be on the paper view for editors, hidden by a disclosure triangle or something like that.

**Comment by marcrohloff** [comment]
Are we handling multiple authors?

**Comment by chrislintott** [comment]
I think if we can we'd get huge value for authors being able to comment on reviews. We should only have one lead author with the authority to submit, though.

**Comment by freelanceastro** [comment]
Still thinking about exactly how to handle multiple authors. But I don't think this issue depends crucially on that.
