### ISSUE TITLE
"Submitted by" is not working in author view

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#196]
A really minor cosmetic thing, but when I'm looking at the list of papers I've submitted, I see this:
![screen shot 2015-05-29 at 2 13 11 pm](https://cloud.githubusercontent.com/assets/3872825/7892854/e0df440c-060c-11e5-8026-2e95cde27ed5.png)
I should see "submitted by NAME on DATE" instead.

**Comment by marcrohloff** [comment]
Should be fixed

**Comment by freelanceastro** [comment]
Yup.
