### ISSUE TITLE
Masthead for the journal

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#197]
We need to say who's behind this project, otherwise we won't be taken seriously.

So:
Peter
Chris
Editorial board
Marc
Arfon
Stuart
Adam

Am I missing anyone?

**Comment by afomi** [comment]
Developers/Contributors

**Comment by marcrohloff** [comment]
Do I need to do anything here?

**Comment by freelanceastro** [comment]
Not yet. This is waiting on a conversation that might not happen for another week or so; once it does happen, I'll provide the text and then we just need to slap it on the About page.
