### ISSUE TITLE
Sidebar highlights wrong section for editors when looking at papers under review

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#201]
If an editor clicks on a paper in the "Papers You Are Editing" section, the paper opens up properly -- but the sidebar switches to "Papers You Are Reviewing" for no reason.

**Comment by marcrohloff** [comment]
Should be done. Not to easy to predict but I'm basing this on your role for the paper. Note when testing that you cn actually have multiple roles on a paper.

**Comment by freelanceastro** [comment]
Looks good.
