### ISSUE TITLE
Use Arxiv IDs instead of SHAs in URLs

### ISSUE THREAD

**Issue by marcrohloff** [openjournals/theoj#205]
We should ideally do this for both API and Web URLs. We will also need to redirect unversioned URLs to versioned URLs

**Comment by marcrohloff** [comment]
Is this the direction we want to take rather than SHAs? I think we need to make sure we are happy with this before we do things like start creating DOIs

How do we want to handle the (future) potential of non-arxiv documents?
i.e. would it make sense to have both api and review uri's in the form
   /api/papers/arxiv/1234.1234v1
and
   /review/arxiv/1234.1234v1

**Comment by freelanceastro** [comment]
I do think this is where we want to go. And I think that format works for API and review uris. @stuartlynn @arfon, any thoughts?

**Comment by marcrohloff** [comment]
This should be done. Both API and web url's are now of the format:
  /review/arxiv:1506.00001v2  (version is optional)
I made it fairly trivial to add a new document source.

This is a huge change, please test carefully
