### ISSUE TITLE
Submit page is broken

### ISSUE THREAD

**Issue by arfon** [openjournals/theoj#206]
I don't seem to be able to submit any new papers right now. There's a JavaScript error when I click the 'submit' button (see screenshot). I can replicate the bug with both Chrome and Safari.

![screen shot 2015-06-10 at 8 26 49 am](https://cloud.githubusercontent.com/assets/4483/8083497/a3ae33bc-0f4a-11e5-865b-363b6e17ec4b.png)

**Comment by arfon** [comment]
@marcrohloff any chance you could look into this asap? It's a blocker on me getting the design work done with David.

**Comment by marcrohloff** [comment]
I've already fixed it locally, I'll get it out today.
​

**Comment by arfon** [comment]
Awesome. Thanks.

**Comment by marcrohloff** [comment]
should be fixed

**Comment by freelanceastro** [comment]
Looks like it.
