### ISSUE TITLE
Links in notification emails don't actually lead to the paper that's been submitted/updated/changed/etc.

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#209]
The links appear to point to the API rather than the papers themselves. So we've got links of the form:
http://beta.theoj.org/api/papers/6c5ddacc1145132d3c54d5fd532e46d2
in the emails, which leads to a mess of JSON rather than any paper.

**Comment by marcrohloff** [comment]
Should work now

**Comment by freelanceastro** [comment]
Looks like it.
