### ISSUE TITLE
Logged-out users see too much stuff in the sidebar

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#217]
Right now, this is what the sidebar shows for logged-out users:
![screen shot 2015-06-26 at 12 02 30 am](https://cloud.githubusercontent.com/assets/3872825/8372284/abf394ec-1b96-11e5-88d5-e35f83c8b0b3.png)
They should only see Home and About.

**Comment by marcrohloff** [comment]
Do we not want a section (or sections) for recent papers and searching cf #146 and #147 ? I think we might be better off merging the help and about into a single section

**Comment by freelanceastro** [comment]
Yes, we do want those sections as well, once they exist. And once we have a masthead (i.e. #197), we'll want that in About, not Home, so let's keep those separate for now.

**Comment by marcrohloff** [comment]
Should be fixes
