### ISSUE TITLE
Editors can't assign themselves as reviewers

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#219]
Editors should be able to do this.

**Comment by marcrohloff** [comment]
I suggest we close this as N/A. Editors and Submittors are always able to do reviewer things like make comments. The exception is that the editor doesn't have a 'review completed' button.

**Comment by freelanceastro** [comment]
Interesting. Hadn't thought of it that way....not sure if I agree. @arfon, @stuartlynn, thoughts?
