### ISSUE TITLE
Editors can't accept papers

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#239]

**Comment by arfon** [comment]
@marcrohloff - I think this is because the paper isn't `under_review?` anymore (see [here](https://github.com/openjournals/theoj/blob/452444f54393a72404c605af24d19d3a24688be2/app/models/annotation.rb#L80)). Perhaps we should allow for the paper state to be `review_complete` also?

**Comment by marcrohloff** [comment]
That piece of code controls when you can change the state of an issue (resolved, unresolved, disputed) not th paper

**Comment by marcrohloff** [comment]
@arfon I tested and this works the way I expect, i.e.
- Paper is in submitted state
* Editor assigns reviewers and then clicks 'start review'
- Paper is in under review state
* Reviewers make comments, etc
* Reviewers click 'Review completed'
* When all reviewers have marked the review completed then the state changes to 'review_completed'
- State is 'review completed'
* Editor can choose to 'Accept' the changes
- Paper goes to 'accepted' state

**Comment by freelanceastro** [comment]
@marcrohloff Did you change anything in the code since this morning? Arfon and I tried this earlier today, with *exactly* that workflow, and it didn't work. @arfon watched the Heroku logs and saw the error messages that came up when I tried to accept the paper -- can you paste those in here?

**Comment by marcrohloff** [comment]
I haven't changed anything. I ran the tests on my local machine.
​

**Comment by marcrohloff** [comment]
Actually there was an issue where attempting to mark a review while not 'under review' as incomplete would look like it was successful but not be. Fix should be in prod.

**Comment by arfon** [comment]
> That piece of code controls when you can change the state of an issue (resolved, unresolved, disputed) not th paper

Right but it _is_ called here in the Paper model to when trying to mark the paper as complete:
https://github.com/openjournals/theoj/blob/master/app/models/paper.rb#L151

**Comment by arfon** [comment]
@marcrohloff I've written a failing test for this over here that demonstrates the issue: https://github.com/openjournals/theoj/pull/247

**Comment by marcrohloff** [comment]
Thanks for tracking that down. I think I've got it fixed now.

**Comment by marcrohloff** [comment]
Although I've fixed this, is the best option to resolve all the comments when a paper is accepted? Maybe it would be useful to see the last state of each comment.
