### ISSUE TITLE
Authors should be able to dispute comments

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#241]
But not resolve them. Right now, they can't do either.

**Comment by marcrohloff** [comment]
I think it is probably beneficial to define this workflow better (who can do what when)

**Comment by marcrohloff** [comment]
This was removed completely in favor of open/closed. Do we still want this issue?

**Comment by arfon** [comment]
> This was removed completely in favor of open/closed. Do we still want this issue?

I think this is good to close.
