### ISSUE TITLE
Papers that haven't been accepted shouldn't be visible to everyone with the URL

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#243]
Right now, anyone with the URL — even people who haven't logged in — can see a paper under review, complete with comments.
Given that the URLs are easy to guess given a paper's arXiv ID, this isn't a good idea. Only the editor, the submittor, and the reviewers of a paper should be able to see it before it's been accepted.

**Comment by marcrohloff** [comment]
Do we really need such a closed system? I don't see why. Also note that
comments will be visible on accepted papers.

**Comment by freelanceastro** [comment]
Unfortunately, I think this is a problem — and seeing comments on accepted papers is definitely a problem. (@arfon & @stuartlynn, please chime in on this, especially if you disagree with me.) We don't want to spook reviewers and submittors, who are used to closed peer review. While we'd probably like to push open peer review in the future, we can't start with that kind of system, or we won't get any adoption. At the very least, we have to make it opt-in — it can't be universal, or even the default, at the start.

Just to be clear: I completely agree that this is silly and unnecessary, but unfortunately it's the way peer review works. For now, we have to work within that system.

**Comment by marcrohloff** [comment]
Then I suggest that we simplify this so that non-assigned users can see the
paper but not the comments. As a follow up, should they be able to see who
the reviewers and editors were?

**Comment by freelanceastro** [comment]
Agreed; since submitted papers are all on the arXiv anyhow, there's no harm in someone finding them on the OJ as long as they can't see the comments. And no, I don't think they should be able to see who the reviewers are — but right now they can't.
