### ISSUE TITLE
No information appears on the Recent Papers page in Firefox or Safari

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#254]
Here's how it's supposed to look (and how it actually looks in Chrome):
![screen shot 2016-01-05 at 5 13 36 pm](https://cloud.githubusercontent.com/assets/3872825/12132535/64ad4c44-b3d1-11e5-9748-e8c6c17344c3.png)
And here's how it looks in Firefox and Safari:
![screen shot 2016-01-05 at 5 14 26 pm](https://cloud.githubusercontent.com/assets/3872825/12132538/6f0e7ac8-b3d1-11e5-9356-80cd9bde3814.png)
Probably related to #253; note the login link missing in the second screenshot. Also note the missing icons on the far left-hand side of the screen in the second screenshot.

**Comment by marcrohloff** [comment]
Both are odd since I developed in FF

**Comment by RaoOfPhysics** [comment]
Can confirm, it works fine in Chromium and Chrome but doesn't appear at all in Firefox and Seamonkey. If it helps, I'm on OS X.
