### ISSUE TITLE
Indicate the version of the accepted paper

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#257]
It's possible for authors to post a new version of a paper on the arXiv _after_ we've accepted their paper at the OJ. We can't prevent this, but we can at least indicate the version of the paper that we accepted. I think this should take the form of a small note in the status bar above the PDF display of accepted papers.

**Comment by marcrohloff** [comment]
The Arxiv id, including the version number is displayed at the top right next to the down arrow

**Comment by freelanceastro** [comment]
Didn't know that persisted in the reader view on accepted papers. Great!
