### ISSUE TITLE
Editors should be able to update papers at any time.

### ISSUE THREAD

**Issue by arfon** [openjournals/theoj#265]
Currently it's only possible for the author to update the paper from the arXiv which isn't ideal - once a review is complete it's entirely reasonable for the editor to want to be able to pull the latest version from the arXiv with the changes that have been made as a result of the review.

**Comment by marcrohloff** [comment]
Are we going to assume that auhor and submittor are the same thing?
Also logic wise, a paper is assigned to a specific editor, but should we say that any editor can take an editorial action.

**Comment by marcrohloff** [comment]
This should be fixed.
