### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by uclanate** [openjournals/theoj#283]
as per instructions on theoj.org,  I'm getting in touch with you folks via GitHub issue :).  I'm very curious about novel publishing / review workflows and wanted to hear this team's thoughts on what's going on in this domain.  I'm currently thinking through (at a conceptual level) how to structure review processes, and how different design elements might lead to different types of user behaviors and use cases. Anyways would love to chat more about this type of stuff, let me know what the best way to do that is!

**Comment by arfon** [comment]
Hey @uclanate. Feel free to email me on arfon.smith@gmail.com to continue this conversation.
