### ISSUE TITLE
Do something magical when dropping an arXiv ID into the submission form

### ISSUE THREAD

**Issue by arfon** [openjournals/theoj#31]
Currently the submission form looks like this:

![screen shot 2015-01-24 at 9 24 44 pm](https://cloud.githubusercontent.com/assets/4483/5890095/87617ef4-a40f-11e4-9b3b-082485d70114.png)

It's not clear why we need to ask people for the title here - can't we just grab this from the arXiv? Also, it's not clear what happens when you put the URL in - _what_ URL should it be? Ideally all of these should work:

- http://arxiv.org/abs/1407.5117
- http://arxiv.org/pdf/1407.5117.pdf
- 1407.5117

**Comment by stuartlynn** [comment]
I think this is because we where building this out as a general purpose peer review system. Now that we are back to focusing on the arxiv again we can implement that magic. The preview page can also help with this I think

**Comment by marcrohloff** [comment]
If we decide to go back to something general purpose maybe we can do
something with JS to only show the title field when its needed.

**Comment by stuartlynn** [comment]
yeah honestly I think we just go hard out on this being for the archive and then refactor for other situations once we show it works.

**Comment by arfon** [comment]
> yeah honestly I think we just go hard out on this being for the archive and then refactor for other situations once we show it works.

:+1:

**Comment by freelanceastro** [comment]
Agreed.

**Comment by marcrohloff** [comment]
+1

**Comment by stuartlynn** [comment]
Ok so to detect the different cases for paper input for the archive I am going to use these three regx patterns. I am not as familiar with the various different quirks of the id system thats used on there as other. @arfon @freelanceastro do these match all the cases we would want? I know they changed the id structure a few years ago, do we care about old id's ? 

paper_page_pattern    = /http\:\/\/arxiv\.org\/abs\/[0-9]{4}\.[0-9]{4}v[0-9]+\.pdf/  [Viz](http://regexper.com/#%2Fhttp%5C%3A%5C%2F%5C%2Farxiv%5C.org%5C%2Fabs%5C%2F%5B0-9%5D%7B4%7D%5C.%5B0-9%5D%7B4%7Dv%5B0-9%5D%2B%5C.pdf%2F)

paper_pdf_pattern     = /http\:\/\/arxiv\.org\/pdf\/[0-9]{4}\.[0-9]{4}v[0-9]+\.pdf/ [Vis](http://regexper.com/#%2Fhttp%5C%3A%5C%2F%5C%2Farxiv%5C.org%5C%2Fpdf%5C%2F%5B0-9%5D%7B4%7D%5C.%5B0-9%5D%7B4%7Dv%5B0-9%5D%2B%5C.pdf%2F)

paper_id_pattern      = /[0-9]{4}\.[0-9]{4}v[0-9]+/ [Viz](http://regexper.com/#%2F%5B0-9%5D%7B4%7D%5C.%5B0-9%5D%7B4%7Dv%5B0-9%5D%2B%2F)

**Comment by marcrohloff** [comment]
Would it make sense to trim whitespace and anchor the regex's? I also think
we should accept https url's. Something like
  /^\s+https?:\/\/ ...  \s+$/

**Comment by stuartlynn** [comment]
Ok here are the updated patterns. Have added in some captures to easily get the version no and id and have made it so that the version number is optional

paper_page_pattern    = /^\s+https?:\/\/arxiv\.org\/abs\/([0-9]{4}\.[0-9]{4})(v[0-9]+)?\.pdf\s+/
paper_pdf_pattern     = /^\s+https?:\/\/arxiv\.org\/pdf\/([0-9]{4}\.[0-9]{4})(v[0-9]+)?\.pdf\s+/ paper_id_pattern      = /^\s+([0-9]{4}\.[0-9]{4})(v[0-9]+)?\s+/

**Comment by stuartlynn** [comment]
Oh one minor tweak to. To trim the whitespace it should be \s*  so we capture when there is no extra white space.
