### ISSUE TITLE
Style up the papers view

### ISSUE THREAD

**Issue by arfon** [openjournals/theoj#32]
It currently looks like this:

![screen shot 2015-01-24 at 9 29 39 pm](https://cloud.githubusercontent.com/assets/4483/5890102/314c70d6-a410-11e4-9cd1-e1714b084e91.png)

**Comment by marcrohloff** [comment]
Arfon, Is there anything specific you would like to see with style changes? I think a larger title would be good and maybe color coding based on stats and role?

**Comment by arfon** [comment]
Yeah that all sounds good. I think it should be really easy for an individual to know whether a paper requires their attention too.
