### ISSUE TITLE
Implement basic mailer to communicate changes of paper state to author etc.

### ISSUE THREAD

**Issue by arfon** [openjournals/theoj#33]
On submission we should email the author with a link back to the paper. We should also update them as the review progresses.

**Comment by marcrohloff** [comment]
Arfon, Do you want me to take over this issue?

**Comment by arfon** [comment]
Happy to but I would't prioritize this over the UI work.

**Comment by marcrohloff** [comment]
Well I have questions on almost every issue in the first milestone.

**Comment by arfon** [comment]
> Well I have questions on almost every issue in the first milestone.

Good point. Please go ahead!

**Comment by marcrohloff** [comment]
What 'from' address do we want to use for this. Do you have something setup on the domain?

**Comment by marcrohloff** [comment]
I found more of a problem. If I understand this http://orcid.org/content/membership-comparison correctly you need to be a basic member to be able tor read (non-public) emails from the orcid data. Although it might be worth testing further this appears to be true even if I make my email public.
So either we need to cut this feature or ask user's to fill in their profile.

**Comment by arfon** [comment]
Yes you're right. I'd forgotten about that. 

I think we should require people to also give us an email address before submission. What do you think?

**Comment by chrislintott** [comment]
Agreed. If we don’t have email, we can’t talk to them, and we’ll need that.

**Comment by arfon** [comment]
> What 'from' address do we want to use for this. Do you have something setup on the domain?

Not yet. I can sort something out

**Comment by freelanceastro** [comment]
We should make it possible for authors to give us more than one email address, in case they want their coauthors to be notified when their paper is modified.

**Comment by marcrohloff** [comment]
Wouldn't it be better to allow them to add collaborators rather than email
addresses?
I'm a bit concerned about this making the project a way to spam people.
​

**Comment by arfon** [comment]
> Wouldn't it be better to allow them to add collaborators rather than email addresses?

I agree. I think we should keep it simple here, a user should have a single email address. If they want to notify collaborators then they should invite them to The OJ.

**Comment by freelanceastro** [comment]
Yep, sounds good.

**Comment by marcrohloff** [comment]
Done you should see the following.
* Submittor gets emails when submitting or updating a paper (different email texts)
* Submittor gets an email when the paper state changes
* Editor and reviewers get email that they have been assigned to a paper
* Editor and reviewers get email when an updated paper has been submitted
There is obviously lots of room to tweak email bodies and subjects

**Comment by freelanceastro** [comment]
Haven't been able to test the reviewer emails, but everything else works, so I'm going to say this is done and we can log a bug report if the reviewer emails turn out to be broken.
