### ISSUE TITLE
Fix text to reflect the real location of the submission form

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#36]
The text on the submission page says that the submission form is "below". The form is actually above the text. Either we correct the text or we correct its location; I think we should do the latter, but if that's hard for some weird reason, let's do the former.

**Comment by stuartlynn** [comment]
Removed this text just now. I think we need some text to replace it but I am probably not the person to write it.

**Comment by stuartlynn** [comment]
closed by #43
