### ISSUE TITLE
Annotations do not reliably appear in the correct locations

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#38]
Any annotation made past the first page of a PDF ends up appearing about 3/4ths of a page lower than the location initially clicked when creating the annotation. This makes it effectively impossible to annotate past the first page of a PDF.

**Comment by marcrohloff** [comment]
This is a little more complicated than I expected. The problem is that the page height changes as it scales. So even if you save an annotation on the first page, resize your browser and reload the page then the annotations move.

**Comment by stuartlynn** [comment]
I think we should be recording the locations as fractions of the page height, that way we can recalculate on resize or as needed. Then we have a event listening for window resize that updates the annotation list with the dimensions of each pdf page.

**Comment by marcrohloff** [comment]
The solution I implemented stores y as a value between 0 and 1. It does not handle pdf's with differing page sizes (for example some pages in landscape)
