### ISSUE TITLE
Allow the author to see a preview of the submitted paper before confirming submission

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#39]
Right now, there's no way for an author to delete an accidental submission. That's probably a good thing; we want to reserve the power of removing a paper from the editorial workflow for the editors. Instead, let's make it hard for an author to submit a paper accidentally. There should be a confirmation screen that pops up on submission, with a view of the PDF, the phrase "Please confirm that this is the paper you want to submit to the Open Journal," and "confirm" and "cancel" buttons.

**Comment by stuartlynn** [comment]
I like this idea. We can definitely render out a preview of the paper and have a confirm step that will make the user think a bit more about what they are doing.

**Comment by stuartlynn** [comment]
Started this in  #45

**Comment by stuartlynn** [comment]
Should be resolved by #46
