### ISSUE TITLE
Make the site work in browsers other than Chrome

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#42]
_Maybe_ we can get away with a site that doesn't work in IE for a beta, but it should at least work in Firefox, and hopefully Safari as well.

**Comment by arfon** [comment]
@stuartlynn - any ideas what this is the case?

**Comment by marcrohloff** [comment]
Not generally sure but on the submit page it looks like the submit button
is invisible because the css is not coming through.

**Comment by stuartlynn** [comment]
Yeah its mostly a css problem the parts of css that deal with the shadow dom aren't implemented natively in Safari or Firefox yet so Polymer shims them but its not picking up some of the styles. This isnt an issue in those browsers in other polymer projects I have seen so I think its an issue with how I am configuring things. Will take a look at it
