### ISSUE TITLE
Fetch details of a paper on save from the arxiv server. 

### ISSUE THREAD

**Issue by stuartlynn** [openjournals/theoj#47]

**Comment by arfon** [comment]
Do you want to do this in a worker or does this need to be done during submission?

**Comment by stuartlynn** [comment]
So there are couple of ways of doing this I think. 




1) The front end already does a call to the arXiv Api ( proxies through the app) to get details for the preview page (before the paper gets saved). We could include the extra arXiv details on the creation request that the preview page makes on submit.  Someone could conceivably mess around with this data in the console before hitting submit so they could send back crap data(do we care ?) 




2) do it on the request and return the paper so the front end uses the details on the paper object at all future requests. Ensures no funny data stuff and that the paper details are immediately available to the front end but might be slow / fail if the arXiv api is down. 




3) do it in a background worker. Means we are ok if things fail, might mean that those details are jot available to the front end. If the front end checks for this and it's not present then hit up the Api directly to grab that info as we are doing on the preview page. 




I am in favour of 1) but would love to know other people's options. 




3) do 



—

**Comment by stuartlynn** [comment]
Currently I am doing it on save in the request cycle.

**Comment by marcrohloff** [comment]
I would be against (1) for the reason you mentioned of people being able to mess around. It would also be nice to have the data available immediately in a different browser/device.

I would suggest (2) for simplicity with (3) as an option if/when performance becomes an issue.

**Comment by marcrohloff** [comment]
In addition if we procy through the app the cost of saving it to a database should be minimal?

**Comment by stuartlynn** [comment]
First attempt at this is up here :  #49
