### ISSUE TITLE
Correct ORCID authorization screen

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#60]
When asking for ORCID authorization on login, the following is displayed:

![screen shot 2015-02-04 at 12 23 27 am](https://cloud.githubusercontent.com/assets/3872825/6035560/17b74ee2-ac04-11e4-88f0-7bfd232cdb61.png)

Obviously it should say The Open Journal. I suspect this is an ORCID OAuth problem, should be easy.

**Comment by arfon** [comment]
Yeah, we need to register another ORCID application. I'll do that.

**Comment by marcrohloff** [comment]
Can't you just edit the details in the current app?


​

**Comment by arfon** [comment]
No because these creds are being used in production over here: http://beta.briefideas.org/

**Comment by arfon** [comment]
Fixed.
