### ISSUE TITLE
Preview page displays XML source of arXiv abstract page rather than PDF

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#62]
![screen shot 2015-02-04 at 12 31 11 am](https://cloud.githubusercontent.com/assets/3872825/6035641/28d11b94-ac05-11e4-98e5-db20dfe1390f.png)

**Comment by marcrohloff** [comment]
Adam, Did this happen for all papers or a specific one? Is it fixed with Stuart's related commit?

**Comment by marcrohloff** [comment]
This appears to be fixed. Closing.
