### ISSUE TITLE
Its currently possible to submit a paper to the system twice. 

### ISSUE THREAD

**Issue by stuartlynn** [openjournals/theoj#65]
Need to fix this and properly report when there is an issue.

**Comment by marcrohloff** [comment]
Are we (can we) do anything to validate authorship of the paper?

**Comment by stuartlynn** [comment]
We could try to match the orcid id name to one of the names in the author list but I would be nervous about doing that. I don’t think we could do it particularly reliably and it would be hugely frustrating if you where trying to submit but couldn’t because of a small name mismatch. 




This could be something the reviewers do though, verify that the submitting person is an author. If not we should give them a way to report that. 




Cheers




Stuart


—

**Comment by marcrohloff** [comment]
Does Arxiv not track orc id's for authors?

Maybe we should probably include a message saying who submitted the paper already.

Going off from what you say about having the reviewers verify who submitted the paper... Apart from annotations would it make sense to have a checklist that is done for every paper (things that should be reviewed for every paper)? We could do this fairly easily by adding a standard (hard-coded) set of annotations to every paper when it is imported.

**Comment by stuartlynn** [comment]
Not sure what the arxiv stores but the response I get form the arxiv gem only gives back the authors names and affiliations. 

I think just creating standard annotations  would confuse the use of the annotations/issues and I think we should be as clear as we can about their intent. If we want to make sure of specific global  things like authorship being valid, proper formatting etc I feel like we should include those as explicit checkboxes that a reviewer can tick off. 

Happy to be persuaded otherwise though as it will mean writing less code @arfon @freelanceastro any thoughts on this?

**Comment by marcrohloff** [comment]
I agree about checkboxes being better. I was mostly thinking about ease of
implementation for a beta.

​

**Comment by arfon** [comment]
I like both ideas to be honest but I understand why you don't like the annotation idea Stuart.

**Comment by freelanceastro** [comment]
I agree with Stuart - I prefer the idea of checkboxes.

**Comment by marcrohloff** [comment]
cf Issue #67

**Comment by marcrohloff** [comment]
@stuartlynn Do you think we should override PaerController#arxi_dDetails to fail if the paper exists? I'm wary of overloading it in this way but it would be the simplest without requiring two requests.

The alternative is to have return an arxiv object either from our internal db or from arxiv if its not there and add an additional flag to indicate the origin.
