### ISSUE TITLE
The sign out link needs to be in a smaller font than the user's name

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#83]
Right now, the upper-right of the screen looks like this for a signed-in user:

![screen shot 2015-02-09 at 9 13 57 am](https://cloud.githubusercontent.com/assets/3872825/6111210/01f1b5fc-b03c-11e4-9065-163b32149618.png)

"Sign out" should be in a significantly smaller font -- otherwise, it's pretty confusing, and not immediately apparent that those are two different links.

**Comment by marcrohloff** [comment]
Can we do something else. Maybe turn logout into a button?
​
