### ISSUE TITLE
Replace the bacon ipsum text on the Home and About pages

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#84]
Bacon ipsum is fun, but it's time for that to go. I'll put some text here soon for us to talk about.

**Comment by chrislintott** [comment]
Happy to take care of this if you'd like.

**Comment by freelanceastro** [comment]
Sure! Thanks.

**Comment by freelanceastro** [comment]
OK, here's a draft of text for the Home and About pages. I made up a few policies, which I think are reasonable, but please have a look at the whole thing and let me know what you all think.
Also, I left a placeholder in for the editorial board.

# HOME:

Welcome to the Open Journal!
The Open Journal is a peer-reviewed, open-access journal for research in cosmology. 

*How does it work?*
The Open Journal makes submitting and reviewing articles fast and easy:
* Submitting to the Open Journal is as easy as posting your article to the arXiv. Just log in here and enter the arXiv ID number, and you’re done!
* Our novel reviewer interface makes it easy for authors and reviewers to discuss articles. You’ll be notified in real time as reviewers make individual comments on your article, dramatically speeding up the process of peer review.
* Revisions are submitted in the same manner as the original article — simply post a new version of your article to the arXiv.
* When your article is accepted, it will appear **immediately** on the Open Journal’s website. You’ll also receive a “badge” on your arXiv abstract page indicating that your article was reviewed by the Open Journal.

# ABOUT:

*What can I submit to the Open Journal?*
If your article is posted on the astro-ph.CO section of the arXiv, it’s an appropriate submission for the Open Journal.

*Who’s on your editorial board?*
<insert list here>
I have a preliminary list, but I don't want to post that kind of information publicly until we've got confirmation from everyone involved.

*What’s the philosophy behind the Open Journal?*
We don’t need journals to disseminate our research anymore; in cosmology, we all post our research to the arXiv. We only need journals for peer review, and the prestige that comes along with that. But traditional journals still have all the trappings of publication, including an unnecessarily slow and expensive editorial process, along with a nasty habit of placing the articles they publish behind a paywall.

The Open Journal does things differently, because we’re not a publisher. Instead, we’re a **peer-review platform**, piggybacking on the arXiv for all the “publishing.” The Open Journal provides peer review for arXiv articles, making the process as fast and easy as we can. Once peer review for a particular article is successfully completed, we mark that article as accepted and send that information to the arXiv. Accepted articles receive a DOI and are listed in ADS, just like in any other journal — but in a fraction of the time, and at a fraction of the cost. 

*What’s “open” about the Open Journal? Is the peer review process itself open?*
The articles are open, in that all articles accepted by the Open Journal are released under a Creative Commons Attribution license. The infrastructure is open too — the code running the Open Journal is available under an MIT License. The reviewer comments can be made open at the joint discretion of the authors and reviewers.

**Comment by marcrohloff** [comment]
As a side comment, none of this text is currently searchable on Google (because it is all loaded from ajax) , do we want to do the extra work required to make it so.

**Comment by stuartlynn** [comment]
Eventually but not right now would be my guess.

**Comment by freelanceastro** [comment]
Yeah, not a priority. Leave that for later.

**Comment by chrislintott** [comment]
Immediate question that needs answering : What if I want my paper reviewed without putting it on arXiv? 

We could support people creating github repos. Or ignore this for now.

**Comment by chrislintott** [comment]
Also : I don't think this is a cosmology journal, but for astrophysics. Text needs broadening beyond .CO

**Comment by freelanceastro** [comment]
I think we ignore that for now. Support for other platforms is definitely something we want eventually, but we don't need it yet.
If we want, we could add something saying that we have future plans to expand past the arXiv, but that raises more questions that we probably don't want to address right now.
And yes, agreed about cosmology -- that was probably just me being cosmology-centric as usual. I'll fix that now.

**Comment by chrislintott** [comment]
I disagree, I think - we'll miss out on a lot of non-cosmologists if we don't have this soon, though I agree we could launch without it. Could we not accept suitably formatted github repos? I'd be much happier if we could at least offer this olive branch. If not...

Suggested answer to the question:

What if I don't want to submit to the arXiv before review?

At the moment, we rely on the arXiv for publication. We'll be expanding to support other platforms including private submission sometime soon, but for now all OJ papers need to be on the arXiv for us to review them. 


Also - with answer stolen from theoj.org

What about copyediting?

Traditional journals place great stress on the quality control they provide beyond peer review - academics in a hurry to get to the next paper or to generally avoid the nitty gritty of publishing rely on journal editorial staff to edit copy, correct references and so on, it's true. But decent copyediting costs a fraction of the fees most journals charge (either directly to author or in the form of expensive library subscriptions), and in any case a large fraction of what's on arXiv and happily being shared are proofs from before that process happens, simply because that's what the author has to hand.

**Comment by freelanceastro** [comment]
Both those answers look good to me. As for the feasibility of accepting github repos out of the gate, I defer to @stuartlynn and @marcrohloff.

**Comment by stuartlynn** [comment]
All we need is a url that points at a pdf, we have hard coded a lot to work with the arxiv in the preview and in grabbing extra data about the paper. Shouldn't be to hard to broaden out but I think we do that after we get Arxiv papers working. I think we can have this for launch or shortly after but would like to not have to think about it till we get the code functionality in place.

**Comment by marcrohloff** [comment]
I would guess that we can easily handle any document that the Google viewer can handle and that has an unauthenticated url. So most text documents and spreadsheets. Github repos would be a problem unless it was a single document file.

**Comment by chrislintott** [comment]
Why don’t we say for now that we’re not supporting anything else, but if people are interested they should contact us/Peter? Then we can gauge demand.

C

**Comment by stuartlynn** [comment]
Well right now we need it to be a PDF. We cant use Google viewer directly I don't think cause it plants an Iframe on the page and doesn't have a good API to access events etc (as far as I know). So using it to mark up a document is going to be hard. We could develop a spreadsheet viewer etc but I dont think we need that. Lets stick to PDF's just now

**Comment by marcrohloff** [comment]
Yes you're right, I was thinking of the submit preview page.

**Comment by freelanceastro** [comment]
OK, let's put the text up there. Here's the text as it stands now, we can make any further changes later.
I didn't include the answer about copyediting because I think that's a level of detail that we don't need to address here now. If anyone disagrees, we can talk about it later, but for now let's get this text on the site.

# HOME:

Welcome to the Open Journal!
The Open Journal is a peer-reviewed, open-access journal for research in astrophysics and cosmology. 

*How does it work?*
The Open Journal makes submitting and reviewing articles fast and easy:
* Submitting to the Open Journal is as easy as posting your article to the arXiv. Just log in here and enter the arXiv ID number, and you’re done!
* Our novel reviewer interface makes it easy for authors and reviewers to discuss articles. You’ll be notified in real time as reviewers make individual comments on your article, dramatically speeding up the process of peer review.
* Revisions are submitted in the same manner as the original article — simply post a new version of your article to the arXiv.
* When your article is accepted, it will appear **immediately** on the Open Journal’s website. You’ll also receive a “badge” on your arXiv abstract page indicating that your article was reviewed by the Open Journal.

# ABOUT:

*What can I submit to the Open Journal?*
If your article is posted on the astro-ph section of the arXiv, it’s an appropriate submission for the Open Journal.

*Who’s on your editorial board?*
To be revealed at launch.

*What’s the philosophy behind the Open Journal?*
We don’t need journals to disseminate our research anymore; in astrophysics and cosmology, we all post our research to the arXiv. We only need journals for peer review, and the prestige that comes along with that. But traditional journals still have all the trappings of publication, including an unnecessarily slow and expensive editorial process, along with a nasty habit of placing the articles they publish behind a paywall.

The Open Journal does things differently, because we’re not a publisher. Instead, we’re a **peer-review platform**, piggybacking on the arXiv for all the “publishing.” The Open Journal provides peer review for arXiv articles, making the process as fast and easy as we can. Once peer review for a particular article is successfully completed, we mark that article as accepted and send that information to the arXiv. Accepted articles receive a DOI and are listed in ADS, just like in any other journal — but in a fraction of the time, and at a fraction of the cost. 

*What’s “open” about the Open Journal? Is the peer review process itself open?*
The articles are open, in that all articles accepted by the Open Journal are released under a Creative Commons Attribution license. The infrastructure is open too — the code running the Open Journal is available under an MIT license. The reviewer comments can be made open at the joint discretion of the authors and reviewers.

*What if I don't want to submit to the arXiv before review?*
At the moment, we rely on the arXiv for publication. We may expand to support other platforms, but for now all OJ papers need to be on the arXiv for us to review them. Please contact us if you'd like to see us support other platforms.

**Comment by marcrohloff** [comment]
I'm adding an h1 title to the about page - it doesn't look right without one
