### ISSUE TITLE
Add editor controls to review page allowing them to assign reviewers and change paper state. 

### ISSUE THREAD

**Issue by stuartlynn** [openjournals/theoj#89]

**Comment by marcrohloff** [comment]
As part of this we need to check that reviewing privileges are working correctly. We don't check the paper state before allowing reviews and I think we don't check the user's role before allowing annotations.

**Comment by stuartlynn** [comment]
I wrote some UI code for looking up users and assigning them. Your right it
doesn't check user role but I think the idea is that any registered user
can be assigned as a reviewer. Should probably have a check that they arent
an author/co-author though.

**Comment by marcrohloff** [comment]
Should we require a user to have email address before they can be assigned as a reviewer.

**Comment by stuartlynn** [comment]
Here is the pull request where I stubbed out some components for editor controls https://github.com/openjournals/theoj/pull/120/files

**Comment by marcrohloff** [comment]
ok, i'll take a look

**Comment by marcrohloff** [comment]
Is there a preference for how to change paper state or should I just make something up?

**Comment by stuartlynn** [comment]
I dont think there is a strong preference. Feel free to implement something

**Comment by marcrohloff** [comment]
Can we clarify the flow of paper states? 
Currently the states are pending (the initial state), submitted, under_review, accepted, rejected.
Firstly I'm not sure where 'submitted' fits in?!?
As far as I can see the flow should be:
* initial state is pending
* pending -> under_review (I assume we want to set has reviewers as a guard)
* under_review -> accepted or rejected

**Comment by arfon** [comment]
I think in this case `pending` is the same as `submitted`.

- initial state is pending/submitted
- pending/submitted -> under_review (editor assigns to a reviewer)
- under_review -> accepted or rejected (editor action)

**Comment by marcrohloff** [comment]
Since I don't know what I'm pending for I'm going to remove that state for now
