### ISSUE TITLE
Visually distinguish comments from their replies

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#93]
Right now, comments and their replies are hard to differentiate:

![screen shot 2015-02-09 at 10 04 06 am](https://cloud.githubusercontent.com/assets/3872825/6112146/0429d94c-b043-11e4-9b99-e62aaa958298.png)

The difference in indentation isn't enough -- we need different colors, or a horizontal rule, or some other kind of visual break. (Maybe this is only showing up this way because I'm replying to my own comment, but this needs to be fixed anyhow.)

**Comment by stuartlynn** [comment]
Yeah there is virtually no styling on the replies just now. This was just to get them functionally working


—

**Comment by marcrohloff** [comment]
I think this is done. We might want to tweak the contrast a bit.
