### ISSUE TITLE
Make comment threads possible?

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#94]
There's no way to reply to a reply to a comment on a paper, as far as I can tell. Do we need this?

**Comment by stuartlynn** [comment]
You can can add a reply to the comment by replying to the issue. Its currently unthreaded but its not clear to me that you want it to be threaded. I like githubs approach of a single thread for a conversation. 


—

**Comment by freelanceastro** [comment]
Fair enough. Let's leave it unthreaded for now and we can revisit this later if users want it.
