### ISSUE TITLE
Create editorial management page with bird's-eye view of all papers

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#95]
Editors need a page where they can:
-- see all submitted papers
-- sort by state (submitted, assigned, accepted, rejected, etc)
-- sort by date of submission
-- sort by author
and probably a few other things too. @arfon and @stuartlynn, thoughts?

**Comment by stuartlynn** [comment]
I think this should be an enhanced version of the papers page for editors rather than an entirely new page. I think the functionality of sorting would be useful for reviewers and submitters as well .


—

**Comment by freelanceastro** [comment]
Agreed, that's a good way to do it.

**Comment by marcrohloff** [comment]
Do we want to show all papers or just those that haven't been accepted?

**Comment by marcrohloff** [comment]
I'm going to remove the role from the list of papers. Its pretty much defined by the page you are viewing anyway.
