### ISSUE TITLE
Auto-deploy master to Heroku

### ISSUE THREAD

**Issue by freelanceastro** [openjournals/theoj#98]

**Comment by stuartlynn** [comment]
This should be set up now. It will require the CI check with travis to deploy but heroku should keep up to date with master now.

**Comment by marcrohloff** [comment]
Should we set the 'treat all requests as local' option to true in prod?
That way it'll be easy to tell if there is a migration failure rather than
just getting a 500 error?

​

**Comment by stuartlynn** [comment]
We might want to use a custom build pack that runs the migrations as well : https://github.com/dtao/rake-db-migrate-buildpack
